version: '3.8'

services:
  backend:
    build: .
    ports:
      - "10000:10000"
    environment:
      - SUPABASE_URL=https://eaufubpzxbgfqtutjalo.supabase.co
      - SUPABASE_ANON_KEY=sb_publishable_51j7QV7dhTacsOpJkfVceA_oFU31WPJ
      - SUPABASE_SERVICE_ROLE_KEY=sb_secret_NeuEJonW2p8YGGyv1551Yg_Ge-BHrXH
      - SUPABASE_STORAGE_BUCKET=images
    restart: unless-stopped
