FROM python:3.11

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["gunicorn", "api.index:app", "-k", "uvicorn.workers.UvicornWorker", "--bind", "0.0.0.0:10000"]